### ISSUE TITLE
How do you add new line in comment?

### ISSUE THREAD

**Issue by ysaunier** [thollander/actions-comment-pull-request#12]
I'm not able to add a new line in a comment, except by adding the tag `<br>`. It doesn't take `\n` or `\r`.

**Comment by marcofranssen** [comment]
you might try using `|`, which is a multiline string in yaml.

So:

```yaml
message: |
  This is
  a multiline
  string
```

**Comment by marcofranssen** [comment]
@ysaunier did above help?
