### ISSUE TITLE
[FEATURE] Add ability to delete and re-create current comment

### ISSUE THREAD

**Issue by ViacheslavKudinov** [thollander/actions-comment-pull-request#159]
Hello,
it will be good if possible to add the behaviour when the comment can be not just replaced, but removed and created again.

Sometimes with long commit history in feature branch it is not obvious is comment actual if one is somewhere on the top.
If we have ability to "move" comment to the last commit which "triggered" comment update it probably can be a little bit more obvious. 

Any feedback is appreciated.

**Comment by thollander** [comment]
Released in `v2.1.0`

**Comment by ViacheslavKudinov** [comment]
Wow!
Thanks @thollander

**Comment by ViacheslavKudinov** [comment]
Hello @thollander 
Im trying this version but I see it just creates new comment and do not delete previous one.
Step looks like:
```
      - name: "Comment PR"
        uses: thollander/actions-comment-pull-request@604a0da6197348d9605c82aa7dcc7f0b5d7d6344 # tag v2.1.0
        if: always()
        with:
          message: |
            ## :microscope: Conftest test on ${{ matrix.folder }}
            ${{ env.STATUS }}
            ```shell
            ${{ steps.result.outputs.RESULT }}
            ```
          pr_number: ${{github.event.number}}
          mode: "recreate"
```
Real comment:

> ## :microscope: Conftest test on organization
> ### :white_check_mark: All tests PASSED !
> ```shell
> 
> 30 tests, 30 passed, 0 warnings, 0 failures, 0 exceptions
> ```

How does it identify which comment to delete?

Previously to update comment I used version with `comment_includes` input and it was a filter to find comment.

Do I do anything wrong now?

**Comment by ViacheslavKudinov** [comment]
The input `comment_tag: Conftest test on ${{ matrix.folder }}` seems helped.
