### ISSUE TITLE
When filePath is absolute GITHUB_WORKSPACE shouldn't be joined

### ISSUE THREAD

**Issue by pfichtner** [thollander/actions-comment-pull-request#176]
When passing `'/tmp/foobar.txt'` as filePath (`filePath: /tmp/foobar.txt`) I got the error 
`Error: ENOENT: no such file or directory, open '/home/runner/work/user/project/tmp/foobar.txt'`

https://github.com/thollander/actions-comment-pull-request/blob/d117ef6afcc405eca3137f55f39a2d4f7d559f6f/src/main.ts#L37

**Comment by pfichtner** [comment]
Is the `join` needed at all? Shouldn't be used `filePath` directly without joining `GITHUB_WORKSPACE`? I guess that way absolute as well relative files should work out of the box!?

**Comment by thollander** [comment]
> Is the `join` needed at all? Shouldn't be used `filePath` directly without joining `GITHUB_WORKSPACE`? I guess that way absolute as well relative files should work out of the box!?

Indeed you're right ! 
Thanks for the feedback. 

Released in https://github.com/thollander/actions-comment-pull-request/releases/tag/v2.3.1
