### ISSUE TITLE
On pull_request_target information

### ISSUE THREAD

**Issue by McGiverGim** [thollander/actions-comment-pull-request#237]
Hi! I only want to explain my problem and the solution, to see if it can be documented in the project and help to others. 

I was stuck with the error `Resource not accessible by integration` and adding the write permission as explained in the readme of your project didn't work. Looking at the GitHub documentation, when the PR comes from a fork, it will have only `read` permission despite the `permissions` given in the action for the `pull_request` event.

The solution was to use the `pull_request_target` event. With this event, I can give write permissions without problem. The difference is that it will execute the action from the "target" branch and not from the origin PR. But this is usually good for the major part of projects.

This is my code change, if you want to look at it: https://github.com/betaflight/betaflight/pull/12851

Maybe this information can be added to the readme to help others like me.

Regards and thanks for your project! It's very useful.

**Comment by thollander** [comment]
Hello,

Thanks for having taking the time to give this feedback, that's always appreciated a lot. 
I'll try to add clear information on this in the README. 

Thanks!
