### ISSUE TITLE
Deletion should delete new comment, not the "updated" one

### ISSUE THREAD

**Issue by koppor** [thollander/actions-comment-pull-request#247]
The deletion does not work if an update happened (of a comment created an another workflow).

Steps:

1. Workflow A creates comment
2. Workflow A ends
3. Workflow B starts (later)
4. Workflow B creates new comment (instead of updating existing one)
5. Workflow B post Action reports successful deletion. Comment from Workflow A is remived. Comment from Workflow B is still there.

![Screenshot_2023-07-03-17-25-11-85_ffb2f5e1b976ff98cfc94f359fbce8de](https://github.com/thollander/actions-comment-pull-request/assets/1366654/80f2ff45-6e76-4a6f-b769-2c7e76d533d5)

Non-MWE: 

https://github.com/JabRef/jabref/pull/10057

State after post action of workflow B

![Screenshot_2023-07-03-17-45-30-76_ffb2f5e1b976ff98cfc94f359fbce8de](https://github.com/thollander/actions-comment-pull-request/assets/1366654/7415fea5-ac14-4ddd-978c-32a9907ca6e8)

**Comment by thollander** [comment]
Shipped in `v2.4.1`
