### ISSUE TITLE
Unable to resolve `master` version

### ISSUE THREAD

**Issue by arcisad** [thollander/actions-comment-pull-request#25]
Is the `master` now `main`?
I get this error when using the action.
Error: Unable to resolve action `thollander/actions-comment-pull-request@master`, unable to find version `master`
If so, then please update the readme in the `Usage` section.

**Comment by fehmianac** [comment]
Hi @arcisad,

You are right.  `thollander/actions-comment-pull-request@main` is working. I have created PR for Readme update.

**Comment by thollander** [comment]
Closed by #23
