### ISSUE TITLE
Allow to silently exit on no PR error

### ISSUE THREAD

**Issue by gregkaczan** [thollander/actions-comment-pull-request#260]
Hey,

Currently, when the action is run on non-PR event the condition below is triggered which exits the action but also throws an error, which is really non-blocking (when used with continue-on-error). In my case, that message confuses users seeing the logs.

https://github.com/thollander/actions-comment-pull-request/blob/8c77f42bbcc27c832a3a5962c8f9a60e34b594f3/src/main.ts#L37

I could of course add an `if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'` on this action step, but then the name of main branch is configurable in GitHub, so this is not really a bulletproof solution.

Would be good if we could decide (via input), whether the message is shown or not.

I would be glad to propose a PR for this change if this seems like a good idea.

**Comment by thollander** [comment]
Hello, 

thanks for the proposal ! 
I get your point, however, I think that should be managed by the workflow itself. You can manage it thanks to a `if` as you mentionned or thanks to filtering for `on: ` events or with `continue-on-error` (not really good as the step will be :x:) 

I fear that doing that would "hide" some unintentional errors and that we should keep the correct error management for this workflow.
