### ISSUE TITLE
Formatting of message

### ISSUE THREAD

**Issue by benjefferies** [thollander/actions-comment-pull-request#291]
It would be great if you could apply some formatting to the comment such a code block, especially when it comes from a file

**Comment by thollander** [comment]
This is actually possible as it relies on Github markdown. 
See this example PR : https://github.com/thollander/actions-comment-pull-request/pull/296#issuecomment-1751711477

To get content from a file, you just need to be able to retrieve your file content and populate as I did in the example PR. 

```yaml
      - name: Comment PR with file content
        uses: ./
        with:
          message: |
            ```ts
            import fs from 'fs';
            import * as github from '@actions/github';
            import * as core from '@actions/core';
            import { GetResponseDataTypeFromEndpointMethod } from '@octokit/types';
            // See https://docs.github.com/en/rest/reactions#reaction-types
            const REACTIONS = ['+1', '-1', 'laugh', 'confused', 'heart', 'hooray', 'rocket', 'eyes'] as const;
            type Reaction = (typeof REACTIONS)[number];
            ```
```
