### ISSUE TITLE
HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by liyishuai** [thollander/actions-comment-pull-request#30]
Config: https://github.com/DIYgod/RSSHub/blob/master/.github/workflows/dependabot-fork.yml
Log: https://github.com/liyishuai/RSSHub/runs/5237459528?check_suite_focus=true#step:4:8
> (node:1) UnhandledPromiseRejectionWarning: HttpError: Resource not accessible by integration
    at /node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by yaauie** [comment]
😞 we're seeing it too ->

Config: https://github.com/elastic/logstash/actions/runs/1918676428/workflow
Log: https://github.com/elastic/logstash/runs/5382090785?check_suite_focus=true

**Comment by thollander** [comment]
This issue is not linked to this particular action. 
It happens when you're trying to run actions inside of a fork for instance and that you don't have the rights on the upstream repo. 

https://github.com/actions/first-interaction/issues/10#issuecomment-545576314
