### ISSUE TITLE
Github actions Verified creator

### ISSUE THREAD

**Issue by gurvinder-dhillon** [thollander/actions-comment-pull-request#334]
Because this actions does not have a verified creator batch, github action workflow throws an error and won't proceed.
"thollander/actions-comment-pull-request@8c77f42bbcc27c832a3a5962c8f9a60e34b594f3 are not allowed to be used"

Could you please submit for publisher verification - https://docs.github.com/en/apps/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization

**Comment by thollander** [comment]
This seems to be only intended to offer paid plan, which is not the case here. 
Also, I'm not publishing this action under any organisation. 

It is maybe because you're sticking to a commit SHA instead of a tag ?
