### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by george-gca** [thollander/actions-comment-pull-request#345]
Basically a warning given by GitHub action execution.

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: thollander/actions-comment-pull-request@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by thollander** [comment]
Shipped into `v2.5.0`
