### ISSUE TITLE
Wrong Release Name

### ISSUE THREAD

**Issue by Disservin** [thollander/actions-comment-pull-request#352]
Hi I think your release has the wrong title.
https://github.com/thollander/actions-comment-pull-request/releases/tag/v2.5.0

Title says `v2.4.3` but tag is `v2.5.0` I think this might confuse people and think 2.4.3 is actually the latest tag?

**Comment by thollander** [comment]
Thanks for the feedback ! 
I fixed it : https://github.com/thollander/actions-comment-pull-request/releases/tag/v2.5.0
