### ISSUE TITLE
Consistent input naming convention

### ISSUE THREAD

**Issue by nitrocode** [thollander/actions-comment-pull-request#386]
Most use snake case and other inputs use camel case. Could the next version have consistent inputs so if we wrap this action, we can also use consistent inputs?

e.g.

```
pr_number
filePath
GITHUB_TOKEN
```

**Comment by thollander** [comment]
Released in `v3.0.0`

**Comment by nitrocode** [comment]
Thanks!

**Comment by nitrocode** [comment]
The readme might need some updates too 

https://github.com/thollander/actions-comment-pull-request?tab=readme-ov-file#comment-a-file-content
