### ISSUE TITLE
Using branches-ignore with comment-pull-request runs workflow when branch is set to be ignored

### ISSUE THREAD

**Issue by jeffvg** [thollander/actions-comment-pull-request#51]
Hi all,
Currently I'm trying to comment on pull request to a master branch and using the "branches-ignore". I'm uncertain if this is github not running my workflow correct or my config. Can you steer me in the right direction?
- If I open a ```hotfix/update``` branch and pull request to master, the workflow runs and places the comment in the PR when it's set to be ignored and no comment should be inserted.

This is the workflow-

name: 'Comment on PR'
on:
  pull_request:
    branches-ignore:
   ```- 'release/**' ```
   ```- 'hotfix/**' ```

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: comment PR if needed
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
           message: 'Thank you for the master PR. We only accept hotfix PRs for master branch. Please switch base branch to dev to get reviews'
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

- the open test PR is here https://github.com/jeffvg/mui5-react17/pull/82
-
thank you

**Comment by thollander** [comment]
Not linked to this repo, but it should be ok from what is see in the docs : https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-branches 

You may try to merge it on your main branch to check if it changes (your workflow that is running may be the one from your main branch and not from the branch of the PR) 

Good luck
